from dataclasses import dataclass
from engine.classifier import ClassificationResult, Intent, Tone
from engine.escalation import EscalationResult


@dataclass
class ResponseStrategy:
    tone_instruction: str       # How the agent should communicate
    opening: str                # Suggested opening line
    action: str                 # What the agent should do next
    collect: list[str]          # Information to collect before proceeding


def get_response_strategy(
    classification: ClassificationResult,
    escalation: EscalationResult,
) -> ResponseStrategy:
    """
    Translate classification and escalation decisions into a concrete response strategy.

    This does not generate the response - it tells the agent how to respond.
    The actual response is generated by the LLM using the system prompt + this strategy as context.

    Separating strategy from generation means we can adjust tone rules
    without touching the LLM prompt, and audit decisions independently.
    """

    # Tone instruction based on player tone
    tone_map = {
        Tone.THREATENING: "Stay calm and professional. Do not engage with the legal threat directly. Acknowledge the frustration and escalate immediately.",
        Tone.ANGRY: "Lead with empathy. Acknowledge the frustration before any troubleshooting. Do not be defensive.",
        Tone.FRUSTRATED: "Acknowledge the repeated difficulty. Be direct about next steps. Avoid generic phrases.",
        Tone.DISTRESSED: "Be warm and reassuring. Prioritise making the player feel heard before moving to resolution.",
        Tone.NEUTRAL: "Professional and efficient. Get to the point without unnecessary padding.",
    }
    tone_instruction = tone_map.get(classification.tone, tone_map[Tone.NEUTRAL])

    # Opening line guidance
    if classification.tone in {Tone.ANGRY, Tone.THREATENING}:
        opening = "Acknowledge the frustration directly in the first sentence. Do not open with a generic greeting."
    elif "repeat_contact" in classification.flags:
        opening = "Acknowledge that this is not their first contact and that this is not acceptable. Take ownership."
    elif "vip_player" in classification.flags:
        opening = "Professional and warm. Acknowledge the issue immediately without excessive formality."
    else:
        opening = "Standard professional greeting followed by acknowledgment of the issue."

    # Action guidance
    if escalation.should_escalate:
        action = f"Escalate to {escalation.team}. Collect required information first. Inform player of next steps and timeframe."
    else:
        # Map intent to Tier 1 action
        action_map = {
            Intent.PAYMENT_ISSUE: "Follow payment troubleshooting steps: restart app, verify transaction ID, check delivery.",
            Intent.ACCOUNT_ACCESS: "Follow account recovery steps based on login method. Do not ask for password.",
            Intent.TECHNICAL_ISSUE: "Follow technical troubleshooting: device info, OS version, cache clear, reinstall.",
            Intent.BUG_REPORT: "Collect reproduction details. Check if issue is isolated or widespread.",
            Intent.GAME_MECHANIC: "Explain mechanic based on knowledge base. Escalate only if mechanic appears broken.",
        }
        action = action_map.get(classification.intent, "Attempt Tier 1 resolution. Escalate if unresolved after standard steps.")

    # Information to collect
    base_collect = ["Player ID"]
    intent_collect_map = {
        Intent.PAYMENT_ISSUE: ["Transaction ID", "Purchase date and amount", "Platform (iOS/Android/direct)"],
        Intent.REFUND_REQUEST: ["Transaction ID", "Purchase date and amount", "Platform", "Whether item was used"],
        Intent.ACCOUNT_ACCESS: ["Login method (Google/Facebook/Apple/email/guest)", "Error message if any"],
        Intent.TECHNICAL_ISSUE: ["Device model", "OS version", "App version", "Description of issue and when it started"],
        Intent.BUG_REPORT: ["Device model", "OS version", "Steps to reproduce", "Whether issue is consistent or intermittent"],
        Intent.BAN_APPEAL: ["Date ban was noticed", "Any prior warnings received"],
        Intent.FRAUD_REPORT: ["Reported player name or ID", "Date and description of incident", "Screenshots if available"],
    }
    collect = base_collect + intent_collect_map.get(classification.intent, [])

    return ResponseStrategy(
        tone_instruction=tone_instruction,
        opening=opening,
        action=action,
        collect=collect,
    )
